import { promises as fs } from "node:fs";
import os from "node:os";
import path from "node:path";
import crypto from "node:crypto";

export type RequestStatus = "pending" | "approved" | "denied" | "expired";

export interface ApprovalRequest {
  id: string;
  action: string;
  reason: string;
  requestedBy?: string;
  status: RequestStatus;
  createdAt: string;
  expiresAt: string;
  decidedAt?: string;
  decisionReason?: string;
}

export function gateDir(): string {
  return process.env.APPROVAL_GATE_DIR ?? path.join(os.homedir(), ".approval-gate");
}

function requestsDir(): string {
  return path.join(gateDir(), "requests");
}

function auditPath(): string {
  return path.join(gateDir(), "audit.jsonl");
}

async function ensureDirs(): Promise<void> {
  await fs.mkdir(requestsDir(), { recursive: true });
}

export async function audit(event: string, data: Record<string, unknown>): Promise<void> {
  await ensureDirs();
  const line = JSON.stringify({ at: new Date().toISOString(), event, ...data });
  await fs.appendFile(auditPath(), line + "\n", "utf8");
}

function requestPath(id: string): string {
  // ids are generated by us; sanitize anyway so a hostile id cannot traverse paths
  const safe = id.replace(/[^a-zA-Z0-9_-]/g, "");
  return path.join(requestsDir(), `${safe}.json`);
}

async function writeRequest(req: ApprovalRequest): Promise<void> {
  await ensureDirs();
  await fs.writeFile(requestPath(req.id), JSON.stringify(req, null, 2), "utf8");
}

/** Applies TTL: a pending request past its expiry becomes expired (persisted). Fail closed. */
async function applyExpiry(req: ApprovalRequest): Promise<ApprovalRequest> {
  if (req.status === "pending" && Date.now() > Date.parse(req.expiresAt)) {
    const expired: ApprovalRequest = { ...req, status: "expired", decidedAt: new Date().toISOString(), decisionReason: "TTL expired" };
    await writeRequest(expired);
    await audit("expired", { id: req.id, action: req.action });
    return expired;
  }
  return req;
}

export async function createRequest(action: string, reason: string, ttlSeconds: number, requestedBy?: string): Promise<ApprovalRequest> {
  const now = new Date();
  const req: ApprovalRequest = {
    id: crypto.randomBytes(6).toString("hex"),
    action,
    reason,
    requestedBy,
    status: "pending",
    createdAt: now.toISOString(),
    expiresAt: new Date(now.getTime() + ttlSeconds * 1000).toISOString(),
  };
  await writeRequest(req);
  await audit("requested", { id: req.id, action, reason, requestedBy });
  return req;
}

export async function getRequest(id: string): Promise<ApprovalRequest | undefined> {
  try {
    const raw = await fs.readFile(requestPath(id), "utf8");
    return await applyExpiry(JSON.parse(raw) as ApprovalRequest);
  } catch {
    return undefined;
  }
}

export async function listRequests(status?: RequestStatus): Promise<ApprovalRequest[]> {
  await ensureDirs();
  const files = await fs.readdir(requestsDir());
  const out: ApprovalRequest[] = [];
  for (const f of files) {
    if (!f.endsWith(".json")) continue;
    const req = await getRequest(f.slice(0, -5));
    if (req && (!status || req.status === status)) out.push(req);
  }
  return out.sort((a, b) => a.createdAt.localeCompare(b.createdAt));
}

export async function decide(id: string, approve: boolean, reason?: string): Promise<ApprovalRequest> {
  const req = await getRequest(id);
  if (!req) throw new Error(`No request with id ${id}`);
  if (req.status !== "pending") throw new Error(`Request ${id} is already ${req.status}`);
  const decided: ApprovalRequest = {
    ...req,
    status: approve ? "approved" : "denied",
    decidedAt: new Date().toISOString(),
    decisionReason: reason,
  };
  await writeRequest(decided);
  await audit(approve ? "approved" : "denied", { id, action: req.action, reason });
  return decided;
}
